/*
 * generated by Xtext
 */
package submission.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import submission.dsl.ui.internal.SubmissionDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SubmissionDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SubmissionDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SubmissionDslActivator.getInstance().getInjector(SubmissionDslActivator.SUBMISSION_DSL_SUBMISSIONDSL);
	}
	
}
