/*
 * generated by Xtext
 */
package submission.dsl.ui.contentassist

import submission.dsl.ui.contentassist.AbstractSubmissionDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SubmissionDslProposalProvider extends AbstractSubmissionDslProposalProvider {
}
