/*
 * generated by Xtext
 */
package submission.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.IXtextEditorCallback;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SubmissionDslUiModule extends submission.dsl.ui.AbstractSubmissionDslUiModule {
	public SubmissionDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	public Class<? extends IXtextEditorCallback> bindIXtextEditorCallback() {
		return SubmissionDSLXtextEditorCallback.class;
	}
}
