/*
* generated by Xtext
*/
package submission.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import submission.dsl.services.SubmissionDslGrammarAccess;

public class SubmissionDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SubmissionDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected submission.dsl.parser.antlr.internal.InternalSubmissionDslParser createParser(XtextTokenStream stream) {
		return new submission.dsl.parser.antlr.internal.InternalSubmissionDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Submission";
	}
	
	public SubmissionDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SubmissionDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
