/*
* generated by Xtext
*/
package submission.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SubmissionDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return submission.dsl.ui.internal.SubmissionDslActivator.getInstance().getInjector("submission.dsl.SubmissionDsl");
	}
	
}
