/*
* generated by Xtext
*/
package submission.dsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import submission.dsl.services.SubmissionDslGrammarAccess;

public class SubmissionDslParser extends AbstractContentAssistParser {
	
	@Inject
	private SubmissionDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected submission.dsl.ui.contentassist.antlr.internal.InternalSubmissionDslParser createParser() {
		submission.dsl.ui.contentassist.antlr.internal.InternalSubmissionDslParser result = new submission.dsl.ui.contentassist.antlr.internal.InternalSubmissionDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getAnswerAccess().getAlternatives(), "rule__Answer__Alternatives");
					put(grammarAccess.getSubmissionAccess().getGroup(), "rule__Submission__Group__0");
					put(grammarAccess.getSubmissionAccess().getGroup_4(), "rule__Submission__Group_4__0");
					put(grammarAccess.getSubmissionAccess().getGroup_5(), "rule__Submission__Group_5__0");
					put(grammarAccess.getSubmissionAccess().getNameAssignment_2(), "rule__Submission__NameAssignment_2");
					put(grammarAccess.getSubmissionAccess().getEMailAssignment_4_1(), "rule__Submission__EMailAssignment_4_1");
					put(grammarAccess.getSubmissionAccess().getAnswerAssignment_5_1(), "rule__Submission__AnswerAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			submission.dsl.ui.contentassist.antlr.internal.InternalSubmissionDslParser typedParser = (submission.dsl.ui.contentassist.antlr.internal.InternalSubmissionDslParser) parser;
			typedParser.entryRuleSubmission();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SubmissionDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SubmissionDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
