/*
 * generated by Xtext
 */
package submission.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SubmissionDslRuntimeModule extends submission.dsl.AbstractSubmissionDslRuntimeModule {

}
