/*
* generated by Xtext
*/
package submission.dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SubmissionDslStandaloneSetup extends SubmissionDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SubmissionDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

